/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BlockalizerGeneration__factory } from "./BlockalizerGeneration__factory";
export { BlockalizerV2__factory } from "./BlockalizerV2__factory";
