/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DefaultOperatorFilterer } from "./DefaultOperatorFilterer";
export type { IOperatorFilterRegistry } from "./IOperatorFilterRegistry";
export type { OperatorFilterer } from "./OperatorFilterer";
