/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as blockalizerV1Sol from "./BlockalizerV1.sol";
export type { blockalizerV1Sol };
import type * as blockalizerV2Sol from "./BlockalizerV2.sol";
export type { blockalizerV2Sol };
import type * as blockalizerV3Sol from "./BlockalizerV3.sol";
export type { blockalizerV3Sol };
import type * as blockalizerV4Sol from "./BlockalizerV4.sol";
export type { blockalizerV4Sol };
import type * as blockalizerV5Sol from "./BlockalizerV5.sol";
export type { blockalizerV5Sol };
import type * as interfaces from "./interfaces";
export type { interfaces };
