/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as blockalizerV1Sol from "./BlockalizerV1.sol";
export type { blockalizerV1Sol };
import type * as blockalizerV2Sol from "./BlockalizerV2.sol";
export type { blockalizerV2Sol };
export type { BlockalizerController } from "./BlockalizerController";
export type { BlockalizerControllerV2 } from "./BlockalizerControllerV2";
export type { BlockalizerControllerV3 } from "./BlockalizerControllerV3";
